# Generated by Django 6.0.4 on 2026-05-27 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPredictionSummary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latest_prediction_label', models.CharField(blank=True, max_length=80, null=True)),
                ('latest_prediction_source', models.CharField(blank=True, help_text='Usually fusion. Fallback can be face, voice, or text.', max_length=30, null=True)),
                ('latest_confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('previous_prediction_label', models.CharField(blank=True, max_length=80, null=True)),
                ('previous_confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('prediction_changed', models.BooleanField(default=False)),
                ('disease_score_matrix_json', models.JSONField(blank=True, null=True)),
                ('modality_winners_json', models.JSONField(blank=True, null=True)),
                ('latest_summary_json', models.JSONField(blank=True, null=True)),
                ('previous_summary_json', models.JSONField(blank=True, null=True)),
                ('trend_json', models.JSONField(blank=True, null=True)),
                ('analysis_count', models.PositiveIntegerField(default=0)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_fusion_prediction', models.ForeignKey(blank=True, db_column='latest_fusion_prediction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prediction_summaries', to='mindspace.fusionprediction')),
                ('latest_screening_session', models.ForeignKey(blank=True, db_column='latest_screening_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prediction_summaries', to='mindspace.platformscreeningsession')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='prediction_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_prediction_summaries',
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='idx_user_pred_summary_user'), models.Index(fields=['-last_analyzed_at'], name='idx_user_pred_summary_time'), models.Index(fields=['latest_prediction_label'], name='idx_user_pred_summary_label')],
            },
        ),
    ]
