# Generated by Django 6.0.4 on 2026-05-23 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0003_pendingsignup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fusionprediction',
            name='fusion_anxiety_score_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='fusionprediction',
            name='fusion_depression_score_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='fusionprediction',
            name='fusion_stress_score_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='fusionprediction',
            name='fusion_bipolar_score_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='fusionprediction',
            name='fusion_suicidal_score_0_100',
        ),
        migrations.RenameField(
            model_name='fusionprediction',
            old_name='predicted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='pcapipelineresult',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='pcapipelineresult',
            name='dimensionality_reduction_metadata',
        ),
        migrations.RemoveField(
            model_name='pcapipelineresult',
            name='reduced_feature_vector',
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='input_feature_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='latency_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='output_feature_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='pca_components',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='pca_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='pca_response_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='phonation_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pca_pipeline_results', to='mindspace.phonationfeature'),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='raw_features_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pcapipelineresult',
            name='status',
            field=models.CharField(default='completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='pcapipelineresult',
            name='screening_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca_pipeline_results', to='mindspace.platformscreeningsession'),
        ),
        migrations.AddConstraint(
            model_name='pcapipelineresult',
            constraint=models.UniqueConstraint(fields=('screening_session', 'phonation_feature'), name='unique_pca_per_session_phonation_feature'),
        ),
        migrations.RemoveField(
            model_name='fusionprediction',
            name='pca_result',
        ),
    ]
