# Generated by Django 6.0.4 on 2026-05-25 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0004_remove_fusionprediction_fusion_anxiety_score_0_100_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiexecutionlog',
            name='activity_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='endpoint_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='external_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='http_method',
            field=models.CharField(default='POST', max_length=10),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='modality',
            field=models.CharField(blank=True, choices=[('face', 'Face'), ('voice', 'Voice'), ('text', 'Text')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='request_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='response_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiexecutionlog',
            name='timeout_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facefeaturevector',
            name='feature_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facialanalysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facialanalysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fusionprediction',
            name='prediction_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fusionprediction',
            name='probabilities_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fusionprediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='retention_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='prediction_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='probabilities_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='raw_response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='stt_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='stt_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voiceanalysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiceanalysisresult',
            name='prediction_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voiceanalysisresult',
            name='probabilities_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceanalysisresult',
            name='raw_response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceanalysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiapiregistry',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiapiregistry',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcapipelineresult',
            name='phonation_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca_pipeline_results', to='mindspace.phonationfeature'),
        ),
        migrations.AlterField(
            model_name='platformscreeningsession',
            name='current_activity',
            field=models.CharField(blank=True, choices=[('check_in', 'Check In'), ('face_video', 'Face Video'), ('voice_phonation', 'Voice Phonation'), ('scenario_voice_response', 'Scenario Voice Response'), ('fusion', 'Fusion'), ('completed', 'Completed'), ('error', 'Error'), ('abandoned', 'Abandoned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=50),
        ),
        migrations.AddIndex(
            model_name='aiapiregistry',
            index=models.Index(fields=['service_type', 'is_active'], name='idx_api_service_active'),
        ),
        migrations.AddIndex(
            model_name='aiapiregistry',
            index=models.Index(fields=['health_status'], name='idx_api_health_status'),
        ),
        migrations.AddIndex(
            model_name='apiexecutionlog',
            index=models.Index(fields=['api', '-created_at'], name='idx_api_logs_api_created'),
        ),
        migrations.AddIndex(
            model_name='apiexecutionlog',
            index=models.Index(fields=['execution_status', '-created_at'], name='idx_api_logs_status_created'),
        ),
        migrations.AddIndex(
            model_name='apiexecutionlog',
            index=models.Index(fields=['modality', '-created_at'], name='idx_api_logs_modality_created'),
        ),
        migrations.AddIndex(
            model_name='modalityresult',
            index=models.Index(fields=['screening_session', 'modality'], name='idx_modality_session_type'),
        ),
        migrations.AddIndex(
            model_name='pcapipelineresult',
            index=models.Index(fields=['screening_session', '-created_at'], name='idx_pca_session_created'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', '-created_at'], name='idx_security_severity_created'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='idx_security_event_created'),
        ),
        migrations.AddConstraint(
            model_name='aiapiregistry',
            constraint=models.UniqueConstraint(fields=('base_url', 'port', 'endpoint_path'), name='unique_api_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='apiexecutionlog',
            constraint=models.CheckConstraint(condition=models.Q(('request_size_bytes__gte', 0), ('request_size_bytes__isnull', True), _connector='OR'), name='api_request_size_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='apiexecutionlog',
            constraint=models.CheckConstraint(condition=models.Q(('response_size_bytes__gte', 0), ('response_size_bytes__isnull', True), _connector='OR'), name='api_response_size_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='modalityresult',
            constraint=models.UniqueConstraint(fields=('screening_session', 'modality'), name='unique_modality_per_screening_session'),
        ),
        migrations.AddConstraint(
            model_name='pcapipelineresult',
            constraint=models.CheckConstraint(condition=models.Q(('input_feature_count__gte', 0)), name='pca_input_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pcapipelineresult',
            constraint=models.CheckConstraint(condition=models.Q(('output_feature_count__gte', 0)), name='pca_output_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='phonationsound',
            constraint=models.UniqueConstraint(fields=('language_code', 'sound_character'), name='unique_language_sound_character'),
        ),
    ]
